version: '3'

services:
  database:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=api
      - MYSQL_USER=hungtx
      - MYSQL_PASSWORD=123
      - MYSQL_ROOT_PASSWORD=123
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - car_api

  web:
    build: .
    ports:
      - "8000:8000"
    networks:
      - car_api
    depends_on:
      - database
    volumes:
      - .:/app


networks:
  car_api:
    driver: bridge

volumes:
  mysql_data:
